/**
 * POST /api/quests/create-from-preview
 * Creates a quest from preview data (generated by generate-with-ai with preview=true)
 */

import { NextResponse } from 'next/server';
import { getPool } from '../../../lib/db';
import { getUserFromToken } from '../../../lib/auth';
import { TABLES } from '../../../lib/db-schema';

const XP_BY_DIFFICULTY = { easy: 50, medium: 100, hard: 200, epic: 400 };

export async function POST(request) {
  const user = getUserFromToken(request);
  if (!user?.userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const sessionId = user.userId;
  const pool = getPool();

  let body = {};
  try {
    body = await request.json();
  } catch (_) {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  const { objectiveId, quest, milestones, tasks } = body;
  if (!objectiveId || !quest || !quest.title) {
    return NextResponse.json(
      { error: 'objectiveId, quest (with title), milestones, and tasks are required' },
      { status: 400 }
    );
  }

  try {
    // Detect user columns
    const goalsCols = await pool.query(
      `SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'goals' AND column_name IN ('user_id', 'session_id')`
    );
    const questsCols = await pool.query(
      `SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'quests' AND column_name IN ('user_id', 'session_id')`
    );
    const goalsUserCol = goalsCols.rows.some((r) => r.column_name === 'user_id') ? 'user_id' : 'session_id';
    const questsUserCol = questsCols.rows.some((r) => r.column_name === 'user_id') ? 'user_id' : 'session_id';

    // Verify objective belongs to user
    const objectiveCheck = await pool.query(
      `SELECT id FROM goals WHERE id::text = $1::text AND (${goalsUserCol})::text = $2::text`,
      [String(objectiveId), String(sessionId)]
    );
    if (objectiveCheck.rows.length === 0) {
      return NextResponse.json({ error: 'Objective not found or access denied' }, { status: 404 });
    }

    // Resolve tables
    let milestonesTable = TABLES.milestones;
    try {
      const msTableResult = await pool.query(
        `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name IN ('quest_milestones', 'milestones')`
      );
      if (msTableResult.rows.some((r) => r.table_name === 'quest_milestones')) {
        milestonesTable = 'quest_milestones';
      } else if (msTableResult.rows.some((r) => r.table_name === 'milestones')) {
        milestonesTable = 'milestones';
      }
    } catch (_) {}

    let tasksTable = TABLES.tasks;
    try {
      const tTableResult = await pool.query(
        `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name IN ('tasks_table', 'tasks')`
      );
      if (tTableResult.rows.some((r) => r.table_name === 'tasks') && !tTableResult.rows.some((r) => r.table_name === 'tasks_table')) {
        tasksTable = 'tasks';
      }
    } catch (_) {}

    const tasksCols = await pool.query(
      `SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1 AND column_name IN ('user_id', 'session_id')`,
      [tasksTable]
    );
    const tasksUserCol = tasksCols.rows.some((r) => r.column_name === 'user_id') ? 'user_id' : 'session_id';

    // Detect quest columns
    const questCols = await pool.query(
      `SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'quests' AND column_name IN ('target_date', 'estimated_xp', 'xp_reward', 'parent_goal_id')`
    );
    const questColNames = questCols.rows.map((r) => r.column_name);
    let hasTargetDate = questColNames.includes('target_date');
    const hasParentGoalId = questColNames.includes('parent_goal_id');
    const xpCol = questColNames.includes('estimated_xp') ? 'estimated_xp' : questColNames.includes('xp_reward') ? 'xp_reward' : null;

    if (!hasTargetDate) {
      try {
        await pool.query('ALTER TABLE quests ADD COLUMN IF NOT EXISTS target_date DATE');
        hasTargetDate = true;
      } catch (alterErr) {
        console.error('[create-from-preview] Could not add target_date column:', alterErr);
        return NextResponse.json(
          { error: 'Could not add target_date column. Please add it manually: ALTER TABLE quests ADD COLUMN target_date DATE;' },
          { status: 400 }
        );
      }
    }

    // Insert quest
    const xp = quest.xp_reward || XP_BY_DIFFICULTY[quest.difficulty] || 100;
    const qCols = [questsUserCol, 'title', 'description', 'difficulty'];
    const qVals = [String(sessionId), quest.title, quest.description || '', quest.difficulty || 'medium'];
    if (hasParentGoalId) {
      qCols.push('parent_goal_id');
      qVals.push(objectiveId);
    }
    if (xpCol) {
      qCols.push(xpCol);
      qVals.push(xp);
    }
    if (hasTargetDate) {
      qCols.push('target_date');
      qVals.push(quest.target_date || (() => { const d = new Date(); d.setDate(d.getDate() + 30); return d.toISOString().slice(0, 10); })());
    }
    const placeholders = qCols.map((_, i) => (i === 0 ? '$1::text' : `$${i + 1}`)).join(', ');
    const questInsert = await pool.query(
      `INSERT INTO quests (${qCols.join(', ')}) VALUES (${placeholders}) RETURNING id, title, description, difficulty`,
      qVals
    );
    const newQuest = questInsert.rows[0];
    const questId = newQuest.id;

    // Insert milestones
    const msColsResult = await pool.query(
      `SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1`,
      [milestonesTable]
    );
    const msCols = msColsResult.rows.map((r) => r.column_name);
    const hasOrderIndex = msCols.includes('order_index');
    for (const m of (milestones || [])) {
      if (hasOrderIndex) {
        await pool.query(
          `INSERT INTO ${milestonesTable} (quest_id, title, description, status, order_index) VALUES ($1, $2, $3, $4, $5)`,
          [questId, m.title, m.description || '', 'pending', m.order_index ?? 0]
        );
      } else {
        await pool.query(
          `INSERT INTO ${milestonesTable} (quest_id, title, description, status) VALUES ($1, $2, $3, $4)`,
          [questId, m.title, m.description || '', 'pending']
        );
      }
    }

    // Insert tasks
    for (const t of (tasks || [])) {
      await pool.query(
        `INSERT INTO ${tasksTable} (${tasksUserCol}, quest_id, title, description, estimated_hours, status) VALUES ($1::text, $2, $3, $4, $5, 'pending')`,
        [String(sessionId), questId, t.title, t.description || '', t.estimated_hours || 1]
      );
    }

    return NextResponse.json({
      success: true,
      quest: {
        id: newQuest.id,
        title: newQuest.title,
        description: newQuest.description,
        difficulty: newQuest.difficulty,
        milestonesCount: milestones?.length || 0,
        tasksCount: tasks?.length || 0
      }
    });
  } catch (err) {
    console.error('[create-from-preview] Error:', err);
    return NextResponse.json(
      { error: err.message || 'Failed to create quest from preview' },
      { status: 500 }
    );
  }
}
